/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.InterfaceController;
import Controller.VendaController;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Cliente;
import Model.FormaDePagamento;
import Model.Livro;
import Model.Venda;
import Model.VendaDinheiro;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author priscylla
 */
public class InterVendaDinheiro extends javax.swing.JFrame {

    /**
     * Creates new form InterVendaDinheiro
     */
    private DefaultTableModel modelo;
    private VendaController vc;
    private ArrayList<Livro> lista;
    private boolean libera;
    private Cliente cliente1;
    private Calendar ca;
    private Date data;
    private boolean terminado;

  
     
    public InterVendaDinheiro() throws Exception {
        initComponents();
        modelo = (DefaultTableModel)tabela.getModel();
        lista = new ArrayList<Livro>();
        vc = new VendaController();
        libera = false;
        cliente1 = null;
        ca = Calendar.getInstance();
        data = ca.getTime();
        terminado = false;
    }
    
    
    public void limpaTabela(){
        
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        
    }
    
    
    public void volta() throws Exception{ //refatoraçao
        setVisible(Boolean.FALSE);
        OpcaoVenda ov = new OpcaoVenda();
        ov.setInter(vc.getInter());
        ov.setVisible(Boolean.TRUE);
    
    
        
    }
    
    
    
    
    public void setInter(InterfaceController f){
        vc.setInter(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        recebido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        troco = new javax.swing.JLabel();
        txtTroco = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria Cultura");
        setResizable(false);

        jLabel3.setText("Cod. Livro");

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Adicionar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel4.setText("Valor: ");

        valor.setText("R$");

        jLabel6.setText("Recebido: ");

        recebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebidoActionPerformed(evt);
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF Cliente");

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(troco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTroco)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(recebido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codigo)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(valor))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(recebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2))
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(troco)
                    .addComponent(txtTroco))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01(1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabel2.setText("Venda à Vista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

       
        
        
        if(vc.getTamArrayLivros(Integer.parseInt(codigo.getText())) > 0){
            double valor2 = vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0).getValor();
             Object [] linha = {vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0).getTitulo()};
            modelo.addRow(linha);
            Livro l1 = vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0);
            lista.add(l1);
            vc.excluirLivro(Integer.parseInt(codigo.getText()));
            
            
          
            
            if(valor.getText().trim().equals("R$")){
                valor.setText(Integer.toString((int) valor2));
            }
            else{
            double valor1 = Double.parseDouble(valor.getText());
            
            double valor3 = valor1+valor2;
            valor.setText(Integer.toString((int) valor3));
            }
                                  
            
            
            
        }
        else{
                    JOptionPane.showMessageDialog(null,"Não temos este livro no Estoque.");
                    
                    }
        
        codigo.setText("");
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

  
    
    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
         
        
        
    }//GEN-LAST:event_codigoActionPerformed

    private void recebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebidoActionPerformed
        
        
        
        
        
    }//GEN-LAST:event_recebidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if((!recebido.equals("")) && lista.size()>0 && terminado){
        
          
          cliente1 = vc.getCliente(cpf.getText());
          
          int cod = vc.geraCodigo();
        
        
          Venda v = new VendaDinheiro(cod,FormaDePagamento.Avista, cliente1, Double.parseDouble(valor.getText())
                , lista, data);
        
          vc.efetuarVenda(v);
        
        
        JOptionPane.showMessageDialog(null,"Venda Realizada.");
        
        cpf.setText("");
        codigo.setText("");
        valor.setText("");
        recebido.setText("");
        txtTroco.setText("");
       limpaTabela();
       
            try {
                volta();
            } catch (Exception ex) {
                Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
            }
       
       
        }else{
            JOptionPane.showMessageDialog(null, "Verifique o campo Recebido ou a lista de Compra.");
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        try{
        
        Double a =  Double.parseDouble(recebido.getText());
         Double b =  Double.parseDouble(valor.getText());
         
        
           
        
        if(lista.size()==0){
            JOptionPane.showMessageDialog(null,"Nenhuma venda contabilizada.");
        
        }
        
               
       
        else if(vc.getCliente(cpf.getText())== null){
            
            
            int i = JOptionPane.showConfirmDialog(null,"Cliente não Cadastrado!\n"
                + "Cadatrar Cliente?");
        if(i == 0){
            CadastrarCliente cc = new CadastrarCliente();
            cc.setInter(vc.getInter());
            cc.setOpcaoVolta(1);
            cc.setCPF(cpf.getText());
            cc.setVisible(Boolean.TRUE);
        
        }
            
            
        
        
        }        
        
        if( a>= b){
            troco.setText("Troco: ");
            txtTroco.setText("R$ "+Double.toString(a-b));
            terminado = true;
        }else{
            JOptionPane.showMessageDialog(null, "Troco inválido.");
        }}catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        if(lista.size()!=0){
            int i = JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Venda?");
            if(i == 0){
                
                vc.adicionarArrayLivros(lista);
                limpaTabela();
                cpf.setText("");
                recebido.setText("");
                codigo.setText("");
                valor.setText("");
                txtTroco.setText("");
                
                
                JOptionPane.showMessageDialog(null, "Venda Cancelada.");
                try {
                    volta();
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        }else{
        
        cpf.setText("");
        recebido.setText("");
        codigo.setText("");
        valor.setText("");
        limpaTabela();
        JOptionPane.showMessageDialog(null, "Venda Cancelada.");
            try {
                volta();
            } catch (Exception ex) {
                Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        }
      
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(lista.size()!=0){
            int i = JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Venda?");
            if(i == 0){
                
                vc.adicionarArrayLivros(lista);
                limpaTabela();
                cpf.setText("");
                recebido.setText("");
                codigo.setText("");
                valor.setText("");
                txtTroco.setText("");
                
                
                JOptionPane.showMessageDialog(null, "Venda Cancelada.");
                try {
                    volta();
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        }else{
        
        cpf.setText("");
        recebido.setText("");
        codigo.setText("");
        valor.setText("");
        limpaTabela();
        JOptionPane.showMessageDialog(null, "Venda Cancelada.");
           try {
               volta();
           } catch (Exception ex) {
               Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
           }
       
        }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterVendaDinheiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterVendaDinheiro().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
                }
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField cpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField recebido;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel troco;
    private javax.swing.JLabel txtTroco;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
