/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InterfaceController;
import Controller.VendaController;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Cartao;
import Model.Cliente;
import Model.FormaDePagamento;
import Model.Livro;
import Model.TipoVendaCartao;
import Model.Venda;
import Model.VendaCartao;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author priscylla
 */
public class InterVendaCartao extends javax.swing.JFrame {

    /**
     * Creates new form InterVendaCartao
     */
    private VendaController vc;
     private DefaultTableModel modelo;
     private ArrayList<Livro> lista;
     private Cartao cartao;
     private double valorCompra;
     private String cpfCompra;
     private boolean cccConfirmado;
     private Cliente cliente;
     private Calendar ca;
    private Date data;
    private boolean cartaoCadastrado;
   
    
    public InterVendaCartao() throws Exception {
        initComponents();
        vc = new VendaController();
        modelo = (DefaultTableModel)tabela.getModel();
        lista = new ArrayList<Livro>();
        cartao = null;
        valorCompra= 0;
        cliente = null;
        cpfCompra = "";
        cccConfirmado = false;
        ca = Calendar.getInstance();
        data = ca.getTime();
         parcela.removeAllItems();
         cartaoCadastrado = false;
        
    }
    
    public void trocaInformacao(ArrayList<Livro> array, String cpf1, double valorC){
      
        lista = array;
        cpfCompra = cpf1;
        valorCompra = valorC;
     
        
        insereNaTabela(array);
      
        numero.setText(Long.toString(cartao.getNumero()));
        valor.setText(Double.toString(valorC));
        cpf.setText(cpf1);
        setParcelas(valorCompra);
 
    }
    
    public void setConfirma(boolean confirma){
        cccConfirmado = confirma;
    }
    
    public void setCartao(Cartao c){
        cartao = c;
        
    }
    
    public void setInter(InterfaceController f){
        vc.setInter(f);
    }
    
    public void setCartaoCadastrado(boolean b){
        cartaoCadastrado = b;
    
                
    }
    
    
    public void insereNaTabela(ArrayList<Livro> array){
    
        for (int i = 0; i < array.size(); i++) {
            Object [] linha = {array.get(i).getTitulo()};
            modelo.addRow(linha);
        }

    }
    
     public int getParcelas(){
    
    if(parcela.getSelectedItem() == null){ return 0;}
    
    return Integer.parseInt(parcela.getSelectedItem().toString());
    
   
    }
    
    
    public void setParcelas(double valor){
         
        
        if(cartao.getTipo() == TipoVendaCartao.CRÉDITO){
         
         if(valor >= 100.00 && valor < 200.00){
              
                parcela.addItem("1");
                parcela.addItem("2");
                parcela.addItem("3");
         
         }
          if(valor >= 200.00 && valor<300.00){
               parcela.addItem("1");
         parcela.addItem("2");
         parcela.addItem("3");
         parcela.addItem("4");
         
         }
          if(valor >= 300.00){
               parcela.addItem("1");
         parcela.addItem("2");
         parcela.addItem("3");
         parcela.addItem("4");
         parcela.addItem("5");
         }
        }
         
     }
    
    
    
    public void volta() throws Exception{ //refatoraçao
        setVisible(Boolean.FALSE);
        OpcaoVenda ov = new OpcaoVenda();
        ov.setInter(vc.getInter());
        ov.setVisible(Boolean.TRUE);
    
    
        
    }
    
    public void limpaTabela(){
        
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        
    }
    
     
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        parcela = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria Cultura - Venda");
        setResizable(false);

        jLabel3.setText("CPF Cliente");

        jLabel4.setText("Código");

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor");

        valor.setText("R$");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jButton2.setText("Cadastrar Cartão");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Voltar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Número Cartão ");

        jLabel7.setText("Parcelas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor))
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numero))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(valor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel7)
                            .addComponent(parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01(1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabel2.setText("Venda á Cartão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(vc.getTamArrayLivros(Integer.parseInt(codigo.getText())) >0){
            double valor2 = vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0).getValor();
                   
             Object [] linha = {vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0).getTitulo()};
            modelo.addRow(linha);
            Livro l1 = vc.getArrayLivros(Integer.parseInt(codigo.getText())).get(0);
            lista.add(l1);
            vc.excluirLivro(Integer.parseInt(codigo.getText()));
            
            
            
          
            
            if(valor.getText().trim().equals("R$")){
                valor.setText(Integer.toString((int) valor2));
            }
            else{
            double valor1 = Double.parseDouble(valor.getText());
            
            double valor3 = valor1+valor2;
            valor.setText(Integer.toString((int) valor3));
            }
                                  
            
            
            
        }
        else{
                    JOptionPane.showMessageDialog(null,"Não temos este livro no Estoque.");
                    
                    }
        
        codigo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
     
               try{     
        if(lista.size()>0){
             
        setVisible(Boolean.FALSE);
        MostrarCartao mc = new MostrarCartao();
        mc.setInter(vc.getInter());
        mc.trocaInformacao(lista, cpf.getText(), Double.parseDouble(valor.getText()));
        mc.setVisible(Boolean.TRUE);
      
        }else{
            JOptionPane.showMessageDialog(null,"Nenhuma Compra realizada!");
        }
        
        
        
        int i = 5;
          if(vc.getCliente(cpf.getText())== null){
        i = JOptionPane.showConfirmDialog(null,"Cliente não Cadastrado!\n"
                + "Cadastrar Cliente?");
     
        
          }
        
        
        if(i == 0 ){
            CadastrarCliente cc = new CadastrarCliente();
            cc.setInter(vc.getInter());
            cc.setOpcaoVolta(1);
            cc.setCPF(cpf.getText());
            cc.setVisible(Boolean.TRUE);
           
        
        }}catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(lista.size()!=0){
            int i = JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Venda?");
            if(i == 0){
                
                vc.adicionarArrayLivros(lista);
                limpaTabela();
                cpf.setText("");
             
                codigo.setText("");
                valor.setText("");
               
                
                JOptionPane.showMessageDialog(null, "Venda Cancelada.");
                try {
                    volta();
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        }else{
        
        cpf.setText("");
        codigo.setText("");
        valor.setText("");
        limpaTabela();
        JOptionPane.showMessageDialog(null, "Venda Cancelada.");
            try {
                volta();
            } catch (Exception ex) {
                Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        }
                                          
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(lista.size()>0 && cartaoCadastrado){
        
          
          cliente = vc.getCliente(cpf.getText());
                //  f.getLivraria().getListaClientes().get(cpf.getText());
          
          int cod = vc.geraCodigo();
         int parcelas = getParcelas();
        
          Venda v = new VendaCartao(cod,FormaDePagamento.Cartao, cliente, 
                  Double.parseDouble(valor.getText())
                , lista, data, cartao, parcelas);
        
         vc.efetuarVenda(v);
        
        JOptionPane.showMessageDialog(null,"Venda Realizada.");
        
        cpf.setText("");
        codigo.setText("");
        valor.setText("");
        limpaTabela();
       
             try {
                 volta();
             } catch (Exception ex) {
                 Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
             }
       
       
        }else{
            JOptionPane.showMessageDialog(null, "Verifique a lista de Compra e/ou Cadastro do Cartão.");
        
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(lista.size()!=0){
            int i = JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Venda?");
            if(i == 0){
                
              
                vc.adicionarArrayLivros(lista);
                limpaTabela();
                cpf.setText("");
             
                codigo.setText("");
                valor.setText("");
               
                
                JOptionPane.showMessageDialog(null, "Venda Cancelada.");
                try {
                    volta();
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        }else{
        
        cpf.setText("");
        codigo.setText("");
        valor.setText("");
        limpaTabela();
        JOptionPane.showMessageDialog(null, "Venda Cancelada.");
            try {
                volta();
            } catch (Exception ex) {
                Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterVendaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterVendaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterVendaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterVendaCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterVendaCartao().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(InterVendaCartao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField cpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numero;
    private javax.swing.JComboBox<String> parcela;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
